[package]
name = "passgen-telegram"
version = "1.0.0"
edition = "2021"
rust-version = "1.83"
license = "MIT"
description = "Telegram bot-service for generating cryptographically secure passwords/tokens and other sets and sequences."
readme = "README.md"
authors = ["Mamontov Konstantin <k@mamont.xyz>"]
homepage = "https://github.com/mammothcoding/passgen-cmd"
repository = "https://github.com/mammothcoding/passgen-cmd"
keywords = ["generator", "password", "token", "crypto-resistant", "telegram-bot"]
categories = ["authentication", "cryptography"]
exclude = [".*"]

[features]
default = ["ctrlc_handler"]
webhooks = ["rand"]
webhooks-axum = ["webhooks", "axum", "tower", "tower-http"]
ctrlc_handler = ["tokio/signal"]
full = [
    "webhooks",
    "webhooks-axum",
    "ctrlc_handler",
]

[dependencies]
teloxide = { version = "0.13", features = ["macros", "webhooks", "webhooks-axum"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
tokio-util = "0.7"
tokio-stream = "0.1.8"
url = "2.2.2"
futures = "0.3.15"
axum = { version = "0.7.0", optional = true }
tower = { version = "0.5.0", optional = true }
tower-http = { version = "0.6.1", features = ["trace"], optional = true }
rand = { version = "0.8.5", optional = true }
env-file-reader = "=0.3.0"
passgen-lib = "1.0.4"

# Reduce the size of the executable  file:
[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = 'abort'
strip = true